name: Build Go

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.24'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
      - run: go build ./...
