name: Gosec

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.24.3'

jobs:
  gosec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Download dependencies
        run: go mod download

      - name: Run Gosec and generate JSON report
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt=sarif -out=results.sarif ./...'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
