name: Gosec

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.24.3'

jobs:
  gosec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Download dependencies
        run: go mod download

      - name: Run Gosec and generate JSON report
        uses: securego/gosec@master
        with:
          args: '-fmt=json -out=gosec-report.json ./...'
        continue-on-error: true

      - name: Check report file
        run: |
          ls -l gosec-report.json
          cat gosec-report.json

      - name: Upload Gosec report
        uses: actions/upload-artifact@v4
        with:
          name: gosec-report
          path: gosec-report.json
