name: Lint Go

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.24.3'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.2

      - name: Download dependencies
        run: go mod download

      - name: Run golangci-lint
        run: golangci-lint run ./...
