name: Semgrep

on:
  workflow_call:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep with SARIF report
        uses: returntocorp/semgrep-action@v1
        with:
          config: |
            p/golang
            p/security-audit
            p/owasp-top-ten
            p/cwe-top-25
          generateSarif: true
          uploadSarif: true
          comment: true
